# Generated by Django 5.2.1 on 2025-06-04 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transaction",
            name="title",
        ),
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(default="untitled transaction", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="transaction",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("income", "Income"), ("expense", "Expense")],
                default="untitled transaction",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
