# Generated by Django 5.2.1 on 2025-06-11 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0002_remove_transaction_title_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(),
        ),
    ]
