# Generated by Django 5.2.1 on 2025-06-17 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracker_app", "0005_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="avatar_url",
            new_name="avatar",
        ),
    ]
